name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - '.vscode'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
    build:
        strategy:
            matrix:
                os: [windows, ubuntu, macos]
                arch: [x64, arm64]
            fail-fast: false
        runs-on: ${{ matrix.os }}-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Use Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install deps
              run: |
                  npm i
                  scripts/fix-arch.sh ${{ matrix.os }} ${{ matrix.arch }}

            - name: Build
              run: |
                  node scripts/build.mjs
            
            - name: Package
              run: |
                  npm run package -- --arch ${{ matrix.arch }}
                  NAME=`ls out`
                  mkdir output
                  tar -C out zcvf output/$NAME.tar.gz $NAME

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: MAA-${{ matrix.os }}-${{ matrix.arch }}
                  path: 'output'
